import { FoodDatabaseItem } from "./types";

export const FOOD_DATABASE: FoodDatabaseItem[] = [
  // Protein
  { name: "Chicken Breast", calories: 165, protein: 31, carbs: 0, fat: 3.6, serving: "100g", category: "protein" },
  { name: "Chicken Thigh", calories: 209, protein: 26, carbs: 0, fat: 11, serving: "100g", category: "protein" },
  { name: "Chicken Wings", calories: 203, protein: 30, carbs: 0, fat: 8, serving: "4 wings", category: "protein" },
  { name: "Ground Turkey", calories: 170, protein: 21, carbs: 0, fat: 9, serving: "100g", category: "protein" },
  { name: "Turkey Breast", calories: 135, protein: 30, carbs: 0, fat: 1, serving: "100g", category: "protein" },
  { name: "Salmon Fillet", calories: 208, protein: 20, carbs: 0, fat: 13, serving: "100g", category: "protein" },
  { name: "Tuna (canned)", calories: 116, protein: 26, carbs: 0, fat: 1, serving: "100g", category: "protein" },
  { name: "Shrimp", calories: 99, protein: 24, carbs: 0, fat: 0.3, serving: "100g", category: "protein" },
  { name: "Tilapia", calories: 128, protein: 26, carbs: 0, fat: 2.7, serving: "100g", category: "protein" },
  { name: "Ground Beef (90% lean)", calories: 176, protein: 20, carbs: 0, fat: 10, serving: "100g", category: "protein" },
  { name: "Ground Beef (80% lean)", calories: 254, protein: 17, carbs: 0, fat: 20, serving: "100g", category: "protein" },
  { name: "Steak (sirloin)", calories: 206, protein: 26, carbs: 0, fat: 11, serving: "100g", category: "protein" },
  { name: "Pork Chop", calories: 231, protein: 25, carbs: 0, fat: 14, serving: "100g", category: "protein" },
  { name: "Bacon", calories: 541, protein: 37, carbs: 1, fat: 42, serving: "100g", category: "protein" },
  { name: "Eggs (2 large)", calories: 143, protein: 13, carbs: 1, fat: 10, serving: "2 large", category: "protein" },
  { name: "Egg Whites (4 large)", calories: 68, protein: 14, carbs: 1, fat: 0, serving: "4 large", category: "protein" },
  { name: "Tofu (firm)", calories: 144, protein: 17, carbs: 3, fat: 9, serving: "100g", category: "protein" },
  { name: "Tempeh", calories: 192, protein: 20, carbs: 8, fat: 11, serving: "100g", category: "protein" },

  // Dairy
  { name: "Greek Yogurt (nonfat)", calories: 100, protein: 17, carbs: 6, fat: 0.7, serving: "1 cup", category: "dairy" },
  { name: "Greek Yogurt (whole)", calories: 220, protein: 20, carbs: 9, fat: 11, serving: "1 cup", category: "dairy" },
  { name: "Whole Milk", calories: 149, protein: 8, carbs: 12, fat: 8, serving: "1 cup", category: "dairy" },
  { name: "Skim Milk", calories: 83, protein: 8, carbs: 12, fat: 0.2, serving: "1 cup", category: "dairy" },
  { name: "Cottage Cheese (low fat)", calories: 163, protein: 28, carbs: 6, fat: 2.3, serving: "1 cup", category: "dairy" },
  { name: "Cheddar Cheese", calories: 113, protein: 7, carbs: 0.4, fat: 9, serving: "1 oz", category: "dairy" },
  { name: "Mozzarella", calories: 85, protein: 6, carbs: 0.7, fat: 6, serving: "1 oz", category: "dairy" },
  { name: "Parmesan", calories: 110, protein: 10, carbs: 1, fat: 7, serving: "1 oz", category: "dairy" },
  { name: "Cream Cheese", calories: 99, protein: 2, carbs: 1.6, fat: 10, serving: "1 oz", category: "dairy" },
  { name: "Butter", calories: 102, protein: 0.1, carbs: 0, fat: 12, serving: "1 tbsp", category: "dairy" },

  // Grains
  { name: "White Rice (cooked)", calories: 206, protein: 4.3, carbs: 45, fat: 0.4, serving: "1 cup", category: "grain" },
  { name: "Brown Rice (cooked)", calories: 216, protein: 5, carbs: 45, fat: 1.8, serving: "1 cup", category: "grain" },
  { name: "Oatmeal (cooked)", calories: 154, protein: 5, carbs: 27, fat: 2.6, serving: "1 cup", category: "grain" },
  { name: "Whole Wheat Bread", calories: 81, protein: 4, carbs: 14, fat: 1.1, serving: "1 slice", category: "grain" },
  { name: "White Bread", calories: 79, protein: 2.7, carbs: 15, fat: 1, serving: "1 slice", category: "grain" },
  { name: "Pasta (cooked)", calories: 220, protein: 8, carbs: 43, fat: 1.3, serving: "1 cup", category: "grain" },
  { name: "Quinoa (cooked)", calories: 222, protein: 8, carbs: 39, fat: 3.6, serving: "1 cup", category: "grain" },
  { name: "Tortilla (flour)", calories: 146, protein: 4, carbs: 24, fat: 3.5, serving: "1 large", category: "grain" },
  { name: "Tortilla (corn)", calories: 52, protein: 1.4, carbs: 11, fat: 0.7, serving: "1 small", category: "grain" },
  { name: "Bagel", calories: 270, protein: 10, carbs: 53, fat: 1.6, serving: "1 medium", category: "grain" },
  { name: "English Muffin", calories: 132, protein: 5, carbs: 26, fat: 1, serving: "1 muffin", category: "grain" },
  { name: "Pancakes", calories: 227, protein: 6, carbs: 28, fat: 10, serving: "2 medium", category: "grain" },
  { name: "Granola", calories: 471, protein: 10, carbs: 64, fat: 20, serving: "1 cup", category: "grain" },
  { name: "Cereal (Cheerios)", calories: 100, protein: 3, carbs: 20, fat: 2, serving: "1 cup", category: "grain" },

  // Fruits
  { name: "Banana", calories: 105, protein: 1.3, carbs: 27, fat: 0.4, serving: "1 medium", category: "fruit" },
  { name: "Apple", calories: 95, protein: 0.5, carbs: 25, fat: 0.3, serving: "1 medium", category: "fruit" },
  { name: "Orange", calories: 62, protein: 1.2, carbs: 15, fat: 0.2, serving: "1 medium", category: "fruit" },
  { name: "Strawberries", calories: 49, protein: 1, carbs: 12, fat: 0.5, serving: "1 cup", category: "fruit" },
  { name: "Blueberries", calories: 84, protein: 1.1, carbs: 21, fat: 0.5, serving: "1 cup", category: "fruit" },
  { name: "Grapes", calories: 104, protein: 1.1, carbs: 27, fat: 0.2, serving: "1 cup", category: "fruit" },
  { name: "Watermelon", calories: 46, protein: 0.9, carbs: 12, fat: 0.2, serving: "1 cup", category: "fruit" },
  { name: "Mango", calories: 99, protein: 1.4, carbs: 25, fat: 0.6, serving: "1 cup", category: "fruit" },
  { name: "Pineapple", calories: 82, protein: 0.9, carbs: 22, fat: 0.2, serving: "1 cup", category: "fruit" },
  { name: "Avocado", calories: 240, protein: 3, carbs: 13, fat: 22, serving: "1 medium", category: "fruit" },
  { name: "Peach", calories: 59, protein: 1.4, carbs: 14, fat: 0.4, serving: "1 medium", category: "fruit" },

  // Vegetables
  { name: "Broccoli", calories: 55, protein: 3.7, carbs: 11, fat: 0.6, serving: "1 cup", category: "vegetable" },
  { name: "Spinach (raw)", calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, serving: "1 cup", category: "vegetable" },
  { name: "Kale (raw)", calories: 33, protein: 2.9, carbs: 6, fat: 0.6, serving: "1 cup", category: "vegetable" },
  { name: "Sweet Potato", calories: 103, protein: 2.3, carbs: 24, fat: 0.1, serving: "1 medium", category: "vegetable" },
  { name: "Potato (baked)", calories: 161, protein: 4.3, carbs: 37, fat: 0.2, serving: "1 medium", category: "vegetable" },
  { name: "Corn", calories: 132, protein: 5, carbs: 29, fat: 1.8, serving: "1 cup", category: "vegetable" },
  { name: "Green Beans", calories: 31, protein: 1.8, carbs: 7, fat: 0.1, serving: "1 cup", category: "vegetable" },
  { name: "Carrots", calories: 52, protein: 1.2, carbs: 12, fat: 0.3, serving: "1 cup", category: "vegetable" },
  { name: "Bell Pepper", calories: 31, protein: 1, carbs: 6, fat: 0.3, serving: "1 medium", category: "vegetable" },
  { name: "Tomato", calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, serving: "1 medium", category: "vegetable" },
  { name: "Cucumber", calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1, serving: "1 cup", category: "vegetable" },
  { name: "Lettuce (romaine)", calories: 8, protein: 0.6, carbs: 1.5, fat: 0.1, serving: "1 cup", category: "vegetable" },
  { name: "Onion", calories: 44, protein: 1.2, carbs: 10, fat: 0.1, serving: "1 medium", category: "vegetable" },
  { name: "Mushrooms", calories: 15, protein: 2.2, carbs: 2.3, fat: 0.2, serving: "1 cup", category: "vegetable" },

  // Snacks & Nuts
  { name: "Peanut Butter", calories: 190, protein: 7, carbs: 7, fat: 16, serving: "2 tbsp", category: "snack" },
  { name: "Almond Butter", calories: 196, protein: 7, carbs: 6, fat: 18, serving: "2 tbsp", category: "snack" },
  { name: "Almonds", calories: 164, protein: 6, carbs: 6, fat: 14, serving: "1 oz (23 nuts)", category: "snack" },
  { name: "Walnuts", calories: 185, protein: 4.3, carbs: 4, fat: 18, serving: "1 oz", category: "snack" },
  { name: "Cashews", calories: 157, protein: 5, carbs: 9, fat: 12, serving: "1 oz", category: "snack" },
  { name: "Trail Mix", calories: 462, protein: 14, carbs: 44, fat: 29, serving: "1 cup", category: "snack" },
  { name: "Protein Bar", calories: 210, protein: 20, carbs: 22, fat: 8, serving: "1 bar", category: "snack" },
  { name: "Protein Shake (whey)", calories: 120, protein: 24, carbs: 3, fat: 1, serving: "1 scoop + water", category: "snack" },
  { name: "Rice Cakes", calories: 35, protein: 0.7, carbs: 7, fat: 0.3, serving: "1 cake", category: "snack" },
  { name: "Dark Chocolate", calories: 170, protein: 2, carbs: 13, fat: 12, serving: "1 oz", category: "snack" },
  { name: "Hummus", calories: 166, protein: 8, carbs: 14, fat: 10, serving: "1/3 cup", category: "snack" },
  { name: "Chips (potato)", calories: 152, protein: 2, carbs: 15, fat: 10, serving: "1 oz", category: "snack" },
  { name: "Popcorn (air-popped)", calories: 31, protein: 1, carbs: 6, fat: 0.4, serving: "1 cup", category: "snack" },
  { name: "Beef Jerky", calories: 116, protein: 9, carbs: 3, fat: 7, serving: "1 oz", category: "snack" },
  { name: "String Cheese", calories: 80, protein: 7, carbs: 1, fat: 5, serving: "1 stick", category: "snack" },

  // Beverages
  { name: "Black Coffee", calories: 2, protein: 0, carbs: 0, fat: 0, serving: "1 cup", category: "beverage" },
  { name: "Coffee with Cream", calories: 52, protein: 0.4, carbs: 0.6, fat: 5, serving: "1 cup", category: "beverage" },
  { name: "Orange Juice", calories: 112, protein: 2, carbs: 26, fat: 0.5, serving: "1 cup", category: "beverage" },
  { name: "Apple Juice", calories: 114, protein: 0.3, carbs: 28, fat: 0.3, serving: "1 cup", category: "beverage" },
  { name: "Protein Smoothie", calories: 250, protein: 30, carbs: 25, fat: 5, serving: "1 large", category: "beverage" },
  { name: "Chocolate Milk", calories: 208, protein: 8, carbs: 26, fat: 8, serving: "1 cup", category: "beverage" },
  { name: "Soda (cola)", calories: 140, protein: 0, carbs: 39, fat: 0, serving: "12 oz", category: "beverage" },
  { name: "Sports Drink", calories: 80, protein: 0, carbs: 21, fat: 0, serving: "12 oz", category: "beverage" },

  // Meals / Common Items
  { name: "Cheeseburger", calories: 535, protein: 28, carbs: 40, fat: 29, serving: "1 burger", category: "meal" },
  { name: "Grilled Chicken Sandwich", calories: 420, protein: 32, carbs: 44, fat: 12, serving: "1 sandwich", category: "meal" },
  { name: "Pizza Slice (cheese)", calories: 285, protein: 12, carbs: 36, fat: 10, serving: "1 slice", category: "meal" },
  { name: "Pizza Slice (pepperoni)", calories: 313, protein: 13, carbs: 35, fat: 13, serving: "1 slice", category: "meal" },
  { name: "Burrito (chicken)", calories: 580, protein: 32, carbs: 62, fat: 20, serving: "1 burrito", category: "meal" },
  { name: "Tacos (beef, 2)", calories: 340, protein: 18, carbs: 28, fat: 16, serving: "2 tacos", category: "meal" },
  { name: "Chicken Nuggets (10)", calories: 470, protein: 22, carbs: 30, fat: 28, serving: "10 pieces", category: "meal" },
  { name: "French Fries (medium)", calories: 365, protein: 4, carbs: 48, fat: 17, serving: "medium", category: "meal" },
  { name: "Caesar Salad", calories: 360, protein: 14, carbs: 18, fat: 26, serving: "1 bowl", category: "meal" },
  { name: "Chicken Salad", calories: 320, protein: 28, carbs: 12, fat: 18, serving: "1 bowl", category: "meal" },
  { name: "Sushi Roll (California)", calories: 255, protein: 9, carbs: 38, fat: 7, serving: "1 roll", category: "meal" },
  { name: "Ramen", calories: 436, protein: 17, carbs: 56, fat: 16, serving: "1 bowl", category: "meal" },
  { name: "Mac & Cheese", calories: 310, protein: 11, carbs: 40, fat: 12, serving: "1 cup", category: "meal" },
  { name: "PB&J Sandwich", calories: 376, protein: 13, carbs: 50, fat: 15, serving: "1 sandwich", category: "meal" },
  { name: "Turkey Sandwich", calories: 346, protein: 22, carbs: 34, fat: 14, serving: "1 sandwich", category: "meal" },
  { name: "Chicken Fried Rice", calories: 340, protein: 14, carbs: 48, fat: 10, serving: "1 cup", category: "meal" },
  { name: "Stir Fry (chicken & veggies)", calories: 280, protein: 24, carbs: 20, fat: 12, serving: "1 cup", category: "meal" },
];
