import { UsdaStoredFood, storeUsdaFoods, updateSyncMeta } from "./usdaDb";

/**
 * Static file path — pre-built USDA database served from Vercel CDN.
 * Generated by: USDA_API_KEY=your_key node scripts/download-usda.mjs
 *
 * Compact format: { v: number, foods: [fdcId, name, cal, protein, carbs, fat, serving, servingGrams, category][] }
 */
const USDA_DATA_URL = "/data/usda-foods.json";

const STORE_BATCH_SIZE = 5000; // IndexedDB write batch size

export interface SyncProgress {
  phase: "fetching" | "storing" | "done" | "error";
  current: number;
  total: number;
  message: string;
}

type CompactFood = [number, string, number, number, number, number, string, number, string];

function expandFood(row: CompactFood): UsdaStoredFood {
  return {
    fdcId: row[0],
    name: row[1],
    nameLower: row[1].toLowerCase(),
    calories: row[2],
    protein: row[3],
    carbs: row[4],
    fat: row[5],
    serving: row[6],
    servingGrams: row[7],
    category: row[8],
  };
}

/**
 * Download the pre-built USDA database from a single static JSON file
 * and populate IndexedDB. Takes ~5-15 seconds instead of hours.
 *
 * The static file is generated once by the developer via scripts/download-usda.mjs
 * and served from Vercel's CDN (auto gzip/brotli compressed).
 */
export async function syncUsdaDatabase(
  onProgress: (progress: SyncProgress) => void,
  signal?: AbortSignal
): Promise<void> {
  // 1. Fetch the static file
  onProgress({ phase: "fetching", current: 0, total: 0, message: "Downloading food database..." });
  console.log("[USDA Sync] Fetching static database from CDN...");

  const res = await fetch(USDA_DATA_URL, { signal });
  if (!res.ok) {
    throw new Error(`Failed to fetch USDA data: ${res.status} ${res.statusText}`);
  }

  const data: { v: number; foods: CompactFood[] } = await res.json();
  const total = data.foods.length;
  console.log(`[USDA Sync] Received ${total.toLocaleString()} foods, storing in IndexedDB...`);

  onProgress({ phase: "storing", current: 0, total, message: `Storing ${total.toLocaleString()} foods...` });

  // 2. Store in IndexedDB in batches
  let stored = 0;
  for (let i = 0; i < total; i += STORE_BATCH_SIZE) {
    if (signal?.aborted) throw new Error("Sync cancelled");

    const batch = data.foods.slice(i, i + STORE_BATCH_SIZE).map(expandFood);
    await storeUsdaFoods(batch);
    stored += batch.length;

    onProgress({
      phase: "storing",
      current: stored,
      total,
      message: `${stored.toLocaleString()} / ${total.toLocaleString()} foods...`,
    });
  }

  // 3. Mark sync complete
  await updateSyncMeta(stored);
  console.log(`[USDA Sync] Complete! ${stored.toLocaleString()} foods saved.`);
  onProgress({ phase: "done", current: stored, total: stored, message: `Done! ${stored.toLocaleString()} foods saved.` });
}
